name: Push Dependabot PRs

permissions:
  contents: read
  pull-requests: write
  issues: write

on:
  push:
    branches: ["**"]

jobs:
    notify-template:
        runs-on: ubuntu-latest
        steps:
            - name: Post comment using GitHub CLI
              run: |
                gh issue comment 35 \
                --repo ONS-Innovation/python-rap-template \
                --body "Dependabot PR has been raised"
