name: Push Dependabot PRs

permissions:
  contents: read
  pull-requests: write
  issues: write

on:
  push:
    branches:
      - "**"

jobs:
    notify-template:
        runs-on: ubuntu-latest
        steps:
            - name: Post comment using GitHub CLI
              env:
                GH_TOKEN: ${{ secrets.PAT || secrets.GITHUB_TOKEN }}
              run: |
                gh issue comment 35 \
                --repo ONS-Innovation/python-rap-template \
                --body "Dependabot PR in [${{ github.repository }}](${{ github.event.pull_request.html_url }})"
