name: Push Dependabot PRs

on:
  push:
    branches:
      - "**"

permissions:
  contents: read

jobs:
  notify-dependabot-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Send repository dispatch
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/ONS-Innovation/python-rap-template/dispatches \
            -d '{
              "event_type": "dependabot_notice",
              "client_payload": {
                "repo": "'"${{ github.repository }}"'",
                "sha": "'"${{ github.sha }}"'",
                "ref": "'"${{ github.ref }}"'"
              }
            }'
