name: Push Dependabot PRs

permissions:
  contents: read
  issues: write
  pull-requests: write

on:
  pull_request:
    types: [opened, reopened]
    branches: ["**"]

jobs:
  create-dependabot-issue:
    if: github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Create issue
        id: create_issue
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ISSUE_URL="https://github.com/${{ github.repository }}/commit/${{ github.sha }}"
          CREATED_URL=$(gh issue create \
            --title "Dependabot PR in ${{ github.repository }}" \
            --body "@joepercival Dependabot PR detected at commit: $ISSUE_URL")